# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['run.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('templates', 'templates'),
        ('static', 'static'),
        ('core', 'core'),
        ('.env.example', '.env.example'),
        ('README.md', 'README.md'),
        ('MT5_SETUP_GUIDE.md', 'MT5_SETUP_GUIDE.md'),
    ],
    hiddenimports=[
        'MetaTrader5',
        'flask',
        'werkzeug',
        'jinja2',
        'numpy',
        'pandas',
        'pandas_ta',
        'core',
        'core.bots',
        'core.brokers',
        'core.data',
        'core.db',
        'core.routes',
        'core.strategies',
        'core.utils',
        'core.ai',
        'core.backtesting',
        'core.education',
        'core.interfaces',
        'core.services',
        'core.seasonal',
        'core.helpers',
        'core.bots.controller',
        'core.bots.trading_bot',
        'core.brokers.base_broker',
        'core.brokers.binance_broker',
        'core.brokers.broker_factory',
        'core.brokers.ctrader_broker',
        'core.brokers.indonesian_brokers',
        'core.brokers.interactive_brokers',
        'core.brokers.tradingview_broker',
        'core.data.chart_data',
        'core.db.connection',
        'core.db.models',
        'core.db.queries',
        'core.ai.ollama_client',
        'core.ai.trading_mentor_ai',
        'core.backtesting.engine',
        'core.backtesting.enhanced_engine',
        'core.education.atr_education',
        'core.utils.mt5',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='QuantumBotX',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    icon=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='QuantumBotX',
)
